// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protons/vacations.proto

package protons

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HenriqueMessage struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HenriqueMessage) Reset()         { *m = HenriqueMessage{} }
func (m *HenriqueMessage) String() string { return proto.CompactTextString(m) }
func (*HenriqueMessage) ProtoMessage()    {}
func (*HenriqueMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_48b8bf8ef8b5e25e, []int{0}
}

func (m *HenriqueMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HenriqueMessage.Unmarshal(m, b)
}
func (m *HenriqueMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HenriqueMessage.Marshal(b, m, deterministic)
}
func (m *HenriqueMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HenriqueMessage.Merge(m, src)
}
func (m *HenriqueMessage) XXX_Size() int {
	return xxx_messageInfo_HenriqueMessage.Size(m)
}
func (m *HenriqueMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_HenriqueMessage.DiscardUnknown(m)
}

var xxx_messageInfo_HenriqueMessage proto.InternalMessageInfo

func (m *HenriqueMessage) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*HenriqueMessage)(nil), "protons.HenriqueMessage")
}

func init() { proto.RegisterFile("protons/vacations.proto", fileDescriptor_48b8bf8ef8b5e25e) }

var fileDescriptor_48b8bf8ef8b5e25e = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xcf, 0x2b, 0xd6, 0x2f, 0x4b, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0xd6, 0x03, 0x8b,
	0x08, 0xb1, 0x43, 0x25, 0x94, 0x94, 0xb9, 0xf8, 0x3d, 0x52, 0xf3, 0x8a, 0x32, 0x0b, 0x4b, 0x53,
	0x7d, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x85, 0x04, 0xb8, 0x98, 0x73, 0x8b, 0xd3, 0x25, 0x18,
	0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0xa3, 0x74, 0x2e, 0x41, 0x98, 0xa2, 0x30, 0x98, 0x41,
	0x42, 0x41, 0x5c, 0x52, 0xe1, 0x19, 0xa9, 0x79, 0x2e, 0xf9, 0x91, 0xf9, 0xa5, 0xc1, 0x25, 0x89,
	0x45, 0x25, 0x91, 0xf9, 0xa5, 0x45, 0x30, 0x69, 0x21, 0x09, 0x3d, 0xa8, 0x0d, 0x7a, 0x68, 0xc6,
	0x4b, 0xe1, 0x94, 0x51, 0x62, 0x48, 0x62, 0x03, 0x4b, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xf5, 0x0c, 0xed, 0xd6, 0xb8, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HenriqueVacationsClient is the client API for HenriqueVacations service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HenriqueVacationsClient interface {
	WhenDoYouStartYourVacation(ctx context.Context, in *HenriqueMessage, opts ...grpc.CallOption) (*HenriqueMessage, error)
}

type henriqueVacationsClient struct {
	cc *grpc.ClientConn
}

func NewHenriqueVacationsClient(cc *grpc.ClientConn) HenriqueVacationsClient {
	return &henriqueVacationsClient{cc}
}

func (c *henriqueVacationsClient) WhenDoYouStartYourVacation(ctx context.Context, in *HenriqueMessage, opts ...grpc.CallOption) (*HenriqueMessage, error) {
	out := new(HenriqueMessage)
	err := c.cc.Invoke(ctx, "/protons.HenriqueVacations/WhenDoYouStartYourVacation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HenriqueVacationsServer is the server API for HenriqueVacations service.
type HenriqueVacationsServer interface {
	WhenDoYouStartYourVacation(context.Context, *HenriqueMessage) (*HenriqueMessage, error)
}

func RegisterHenriqueVacationsServer(s *grpc.Server, srv HenriqueVacationsServer) {
	s.RegisterService(&_HenriqueVacations_serviceDesc, srv)
}

func _HenriqueVacations_WhenDoYouStartYourVacation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HenriqueMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HenriqueVacationsServer).WhenDoYouStartYourVacation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protons.HenriqueVacations/WhenDoYouStartYourVacation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HenriqueVacationsServer).WhenDoYouStartYourVacation(ctx, req.(*HenriqueMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _HenriqueVacations_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protons.HenriqueVacations",
	HandlerType: (*HenriqueVacationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WhenDoYouStartYourVacation",
			Handler:    _HenriqueVacations_WhenDoYouStartYourVacation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protons/vacations.proto",
}
