// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protons/vacations.proto

package protons

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VacationRequest struct {
	Name                 *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VacationRequest) Reset()         { *m = VacationRequest{} }
func (m *VacationRequest) String() string { return proto.CompactTextString(m) }
func (*VacationRequest) ProtoMessage()    {}
func (*VacationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_48b8bf8ef8b5e25e, []int{0}
}

func (m *VacationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VacationRequest.Unmarshal(m, b)
}
func (m *VacationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VacationRequest.Marshal(b, m, deterministic)
}
func (m *VacationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VacationRequest.Merge(m, src)
}
func (m *VacationRequest) XXX_Size() int {
	return xxx_messageInfo_VacationRequest.Size(m)
}
func (m *VacationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VacationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VacationRequest proto.InternalMessageInfo

func (m *VacationRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type VacationResponse struct {
	Reply                *string  `protobuf:"bytes,1,req,name=reply" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VacationResponse) Reset()         { *m = VacationResponse{} }
func (m *VacationResponse) String() string { return proto.CompactTextString(m) }
func (*VacationResponse) ProtoMessage()    {}
func (*VacationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48b8bf8ef8b5e25e, []int{1}
}

func (m *VacationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VacationResponse.Unmarshal(m, b)
}
func (m *VacationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VacationResponse.Marshal(b, m, deterministic)
}
func (m *VacationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VacationResponse.Merge(m, src)
}
func (m *VacationResponse) XXX_Size() int {
	return xxx_messageInfo_VacationResponse.Size(m)
}
func (m *VacationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VacationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VacationResponse proto.InternalMessageInfo

func (m *VacationResponse) GetReply() string {
	if m != nil && m.Reply != nil {
		return *m.Reply
	}
	return ""
}

func init() {
	proto.RegisterType((*VacationRequest)(nil), "protons.VacationRequest")
	proto.RegisterType((*VacationResponse)(nil), "protons.VacationResponse")
}

func init() { proto.RegisterFile("protons/vacations.proto", fileDescriptor_48b8bf8ef8b5e25e) }

var fileDescriptor_48b8bf8ef8b5e25e = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xcf, 0x2b, 0xd6, 0x2f, 0x4b, 0x4c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0xd6, 0x03, 0x8b,
	0x08, 0xb1, 0x43, 0x25, 0x94, 0x54, 0xb9, 0xf8, 0xc3, 0xa0, 0x72, 0x41, 0xa9, 0x85, 0xa5, 0xa9,
	0xc5, 0x25, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0x9c,
	0x41, 0x60, 0xb6, 0x92, 0x06, 0x97, 0x00, 0x42, 0x59, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90,
	0x08, 0x17, 0x6b, 0x51, 0x6a, 0x41, 0x4e, 0x25, 0x54, 0x21, 0x84, 0x63, 0x94, 0x86, 0x30, 0x30,
	0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0x28, 0x98, 0x4b, 0x2a, 0x3c, 0x23, 0x35, 0xcf, 0x25,
	0x3f, 0x32, 0xbf, 0x34, 0xb8, 0x24, 0xb1, 0xa8, 0x24, 0x32, 0xbf, 0xb4, 0x08, 0xa6, 0x48, 0x48,
	0x42, 0x0f, 0xea, 0x16, 0x3d, 0x34, 0x87, 0x48, 0x49, 0x62, 0x91, 0x81, 0xd8, 0xad, 0xc4, 0x00,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x85, 0x10, 0x18, 0xc2, 0xdb, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VacationServiceClient is the client API for VacationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VacationServiceClient interface {
	WhenDoYouStartYourVacation(ctx context.Context, in *VacationRequest, opts ...grpc.CallOption) (*VacationResponse, error)
}

type vacationServiceClient struct {
	cc *grpc.ClientConn
}

func NewVacationServiceClient(cc *grpc.ClientConn) VacationServiceClient {
	return &vacationServiceClient{cc}
}

func (c *vacationServiceClient) WhenDoYouStartYourVacation(ctx context.Context, in *VacationRequest, opts ...grpc.CallOption) (*VacationResponse, error) {
	out := new(VacationResponse)
	err := c.cc.Invoke(ctx, "/protons.VacationService/WhenDoYouStartYourVacation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VacationServiceServer is the server API for VacationService service.
type VacationServiceServer interface {
	WhenDoYouStartYourVacation(context.Context, *VacationRequest) (*VacationResponse, error)
}

func RegisterVacationServiceServer(s *grpc.Server, srv VacationServiceServer) {
	s.RegisterService(&_VacationService_serviceDesc, srv)
}

func _VacationService_WhenDoYouStartYourVacation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VacationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VacationServiceServer).WhenDoYouStartYourVacation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protons.VacationService/WhenDoYouStartYourVacation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VacationServiceServer).WhenDoYouStartYourVacation(ctx, req.(*VacationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VacationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protons.VacationService",
	HandlerType: (*VacationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WhenDoYouStartYourVacation",
			Handler:    _VacationService_WhenDoYouStartYourVacation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protons/vacations.proto",
}
