# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protons/vacations.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protons/vacations.proto',
  package='protons',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x17protons/vacations.proto\x12\x07protons\"\x1f\n\x0fVacationRequest\x12\x0c\n\x04name\x18\x01 \x02(\t\"!\n\x10VacationResponse\x12\r\n\x05reply\x18\x01 \x02(\t2f\n\x0fVacationService\x12S\n\x1aWhenDoYouStartYourVacation\x12\x18.protons.VacationRequest\x1a\x19.protons.VacationResponse\"\x00')
)




_VACATIONREQUEST = _descriptor.Descriptor(
  name='VacationRequest',
  full_name='protons.VacationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='protons.VacationRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=67,
)


_VACATIONRESPONSE = _descriptor.Descriptor(
  name='VacationResponse',
  full_name='protons.VacationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='protons.VacationResponse.reply', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['VacationRequest'] = _VACATIONREQUEST
DESCRIPTOR.message_types_by_name['VacationResponse'] = _VACATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VacationRequest = _reflection.GeneratedProtocolMessageType('VacationRequest', (_message.Message,), dict(
  DESCRIPTOR = _VACATIONREQUEST,
  __module__ = 'protons.vacations_pb2'
  # @@protoc_insertion_point(class_scope:protons.VacationRequest)
  ))
_sym_db.RegisterMessage(VacationRequest)

VacationResponse = _reflection.GeneratedProtocolMessageType('VacationResponse', (_message.Message,), dict(
  DESCRIPTOR = _VACATIONRESPONSE,
  __module__ = 'protons.vacations_pb2'
  # @@protoc_insertion_point(class_scope:protons.VacationResponse)
  ))
_sym_db.RegisterMessage(VacationResponse)



_VACATIONSERVICE = _descriptor.ServiceDescriptor(
  name='VacationService',
  full_name='protons.VacationService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=104,
  serialized_end=206,
  methods=[
  _descriptor.MethodDescriptor(
    name='WhenDoYouStartYourVacation',
    full_name='protons.VacationService.WhenDoYouStartYourVacation',
    index=0,
    containing_service=None,
    input_type=_VACATIONREQUEST,
    output_type=_VACATIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VACATIONSERVICE)

DESCRIPTOR.services_by_name['VacationService'] = _VACATIONSERVICE

# @@protoc_insertion_point(module_scope)
